# Generated by Django 6.0.4 on 2026-04-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('pizza', 'Pizza'), ('burger', 'Burger'), ('fries', 'Fries'), ('sandwich', 'Sandwich'), ('shawarma', 'Shawarma')], max_length=20)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('regular', 'Regular')], default='regular', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_popular', models.BooleanField(default=False)),
                ('order_type', models.CharField(choices=[('takeaway', 'Take Away'), ('delivery', 'Delivery'), ('dining', 'Dining')], default='takeaway', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
